/**
 * @aiq.webdesigner
 * This script requires AIQ Web Designer
*/
setShadowDOM(true);
navigateTo("https://demosite.appvance.net/");
click(fallback(`span(0, _in(div("product_1")))`,
   `span(0, _in(div({'id':'product_1'})))`,
   `span("Ruby on Rails Tote")`,
   `span("info")`,
   `span("Ruby on Rails Tote")`,
   `byXPath("//div[@id='product_1']/div/div[1]/a/span")`,
   `byXPath('//*[@class="info"]')`,
   `byXPath('//*[text()="Ruby on Rails Tote"]')`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div/div/a/span')`,
   `byXPath("id('product_1')/div[@class='panel panel-default']/div[@class='panel-body text-center product-body']/a[1]/span[@class='info']")`,
   `span({'itemprop':'name'})`,
   `byJQuery('span[title="Ruby on Rails Tote"]')`,
   `byJQuery('span[class="info"]')`,
   `byJQuery('.info')`));
setValue(fallback(`byXPath('//*[@id="quantity"]')`,
   `numberbox("form-control title")`,
   `byXPath('//*[@name="quantity"]')`,
   `numberbox("quantity")`,
   `numberbox("quantity")`,
   `byXPath("//input[@id='quantity']")`,
   `byXPath('//*[@class="title form-control"]')`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div/div[2]/form/div/div/div[2]/div/input')`,
   `byXPath("id('quantity')")`,
   `numberbox({'min':'1'})`,
   `byJQuery('div[class="row"] > div[class="col-md-5"] > div[class="add-to-cart"] > div[class="input-group"] > input[class="title form-control"]')`,
   `byJQuery('#quantity')`,
   `byJQuery('input[name="quantity"]')`),"2");
click(fallback(`submit(0, _in(div("inside-product-cart-form")))`,
   `submit(0, _in(div({'id':'inside-product-cart-form'})))`,
   `byXPath('//*[@id="add-to-cart-button"]')`,
   `submit("btn btn-success[1]")`,
   `byXPath('//*[@name="button"]')`,
   `submit("add-to-cart-button")`,
   `submit("button")`,
   `submit("Add To Cart")`,
   `byXPath("//button[@id='add-to-cart-button']")`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div/div[2]/form/div/div/div[2]/div/span/button')`,
   `byXPath("id('add-to-cart-button')")`,
   `byJQuery('div[class="col-md-5"] > div[class="add-to-cart"] > div[class="input-group"] > span[class="input-group-btn"] > button[class="btn btn-success"]')`,
   `byJQuery('#add-to-cart-button')`,
   `byJQuery('button[name="button"]')`));
click(fallback(`link(0, _in(paragraph("clear_cart_link")))`,
   `link(0, _in(paragraph({'id':'clear_cart_link'})))`,
   `link("continue")`,
   `link("/products")`,
   `link("Continue shopping")`,
   `byXPath("//p[@id='clear_cart_link']/a")`,
   `byXPath('//*[@class="continue"]')`,
   `byXPath('//*[text()="Continue shopping"]')`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/form/p/a')`,
   `byXPath("id('clear_cart_link')/a[@class='continue']")`,
   `byJQuery('a[class="continue"]')`,
   `byJQuery('#clear_cart_link > .continue')`,
   `byJQuery('a[href="/products"]')`));
click(fallback(`span(0, _in(div("product_2")))`,
   `span(0, _in(div({'id':'product_2'})))`,
   `span("Ruby on Rails Bag")`,
   `span("info[1]")`,
   `span("Ruby on Rails Bag")`,
   `byXPath("//div[@id='product_2']/div/div[1]/a/span")`,
   `byXPath('//*[text()="Ruby on Rails Bag"]')`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div[2]/div/div/a/span')`,
   `byXPath("id('product_2')/div[@class='panel panel-default']/div[@class='panel-body text-center product-body']/a[1]/span[@class='info']")`,
   `byJQuery('span[title="Ruby on Rails Bag"]')`));
click(fallback(`submit(0, _in(div("inside-product-cart-form")))`,
   `submit(0, _in(div({'id':'inside-product-cart-form'})))`,
   `byXPath('//*[@id="add-to-cart-button"]')`,
   `submit("btn btn-success[1]")`,
   `byXPath('//*[@name="button"]')`,
   `submit("add-to-cart-button")`,
   `submit("button")`,
   `submit("Add To Cart")`,
   `byXPath("//button[@id='add-to-cart-button']")`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div/div[2]/form/div/div/div[2]/div/span/button')`,
   `byXPath("id('add-to-cart-button')")`,
   `byJQuery('div[class="col-md-5"] > div[class="add-to-cart"] > div[class="input-group"] > span[class="input-group-btn"] > button[class="btn btn-success"]')`,
   `byJQuery('#add-to-cart-button')`,
   `byJQuery('button[name="button"]')`));
click(fallback(`link(0, _in(paragraph("clear_cart_link")))`,
   `link(0, _in(paragraph({'id':'clear_cart_link'})))`,
   `link("continue")`,
   `link("/products")`,
   `link("Continue shopping")`,
   `byXPath("//p[@id='clear_cart_link']/a")`,
   `byXPath('//*[@class="continue"]')`,
   `byXPath('//*[text()="Continue shopping"]')`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/form/p/a')`,
   `byXPath("id('clear_cart_link')/a[@class='continue']")`,
   `byJQuery('a[class="continue"]')`,
   `byJQuery('#clear_cart_link > .continue')`,
   `byJQuery('a[href="/products"]')`));
clickXY(fallback(`image(0, _in(div("product_3")))`,
   `image(0, _in(div({'id':'product_3'})))`,
   `image("Ruby on Rails Baseball Jersey")`,
   `image("https://demosite.appvance.net/spree/products/24/small/ror_baseball.jpeg?1527769327")`,
   `byXPath("//div[@id='product_3']/div/div[1]/a/img")`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div[3]/div/div/a/img')`,
   `byXPath("id('product_3')/div[@class='panel panel-default']/div[@class='panel-body text-center product-body']/a[1]/img[1]")`,
   `image({'src':'/spree/products/24/small/ror_baseball.jpeg?1527769327'})`,
   `byJQuery('img[alt="Ruby on Rails Baseball Jersey"]')`),"87,67");
setValue(fallback(`byXPath('//*[@id="quantity"]')`,
   `numberbox("form-control title")`,
   `byXPath('//*[@name="quantity"]')`,
   `numberbox("quantity")`,
   `numberbox("quantity")`,
   `byXPath("//input[@id='quantity']")`,
   `byXPath('//*[@class="title form-control"]')`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div/div[2]/form/div/div[2]/div[2]/div/input')`,
   `byXPath("id('quantity')")`,
   `numberbox({'min':'1'})`,
   `byJQuery('div[class="row"] > div[class="col-md-5"] > div[class="add-to-cart"] > div[class="input-group"] > input[class="title form-control"]')`,
   `byJQuery('#quantity')`,
   `byJQuery('input[name="quantity"]')`,
   `byJQuery('input[value="1"]')`),"2");
click(fallback(`submit(0, _in(div("inside-product-cart-form")))`,
   `submit(0, _in(div({'id':'inside-product-cart-form'})))`,
   `byXPath('//*[@id="add-to-cart-button"]')`,
   `submit("btn btn-success[1]")`,
   `byXPath('//*[@name="button"]')`,
   `submit("add-to-cart-button")`,
   `submit("button")`,
   `submit("Add To Cart")`,
   `byXPath("//button[@id='add-to-cart-button']")`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div/div[2]/form/div/div[2]/div[2]/div/span/button')`,
   `byXPath("id('add-to-cart-button')")`,
   `byJQuery('div[class="col-md-5"] > div[class="add-to-cart"] > div[class="input-group"] > span[class="input-group-btn"] > button[class="btn btn-success"]')`,
   `byJQuery('#add-to-cart-button')`,
   `byJQuery('button[name="button"]')`));
click(fallback(`span(0, _in(link("delete_line_item_655512")))`,
   `span(0, _in(link({'id':'delete_line_item_655512'})))`,
   `span("glyphicon glyphicon-minus-sign[2]")`,
   `byXPath("//a[@id='delete_line_item_655512']/span")`,
   `byXPath('/html/body/div[2]/div/div/div/div/form/div/div/table/tbody/tr[3]/td[6]/a/span')`,
   `byXPath("id('delete_line_item_655512')/span[@class='glyphicon glyphicon-minus-sign']")`,
   `byJQuery('#delete_line_item_655512 > .glyphicon.glyphicon-minus-sign')`));
setValue(fallback(`byXPath('//*[@id="order_email"]')`,
   `emailbox("form-control title")`,
   `byXPath('//*[@name="order[email]"]')`,
   `emailbox("order_email")`,
   `emailbox("order[email]")`,
   `byXPath("//input[@id='order_email']")`,
   `byXPath('//*[@class="form-control title"]')`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div[2]/form/p/input')`,
   `byXPath("id('order_email')")`,
   `byJQuery('input[class="form-control title"]')`,
   `byJQuery('#order_email')`,
   `byJQuery('input[name="order[email]"]')`),"demo@appvance.net");
click(fallback(`submit("btn btn-block btn-lg btn-success[1]")`,
   `submit("commit[1]")`,
   `submit("Continue")`,
   `byXPath("//form[@id='checkout_form_registration']/p[2]/input")`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div[2]/form/p[2]/input')`,
   `byXPath("id('checkout_form_registration')/p[2]/input[@class='btn btn-lg btn-success btn-block']")`,
   `submit({'data-disable-with':'Continue'})`,
   `byJQuery('input[value="Continue"]')`));
